import { LoadingSpinner, OverlayElement } from './loading';
import { CreatePage, ErrorView, MainPage, PetitionApp } from './layoutWidgets';
import { ConnectionPage, LandingPage, RegistryChooser, IdentityPage } from './setup';
import { IDPWidget, InformationalInfobar, NavigationBar, PeriodWidget } from './nav';
import { Petition } from './petition';
import { PerfMeasure } from './perf';

customElements.define("petition-app", PetitionApp);
customElements.define("landing-page", LandingPage);
customElements.define("informational-infobar", InformationalInfobar);
customElements.define("navigation-bar", NavigationBar);
customElements.define("connection-page", ConnectionPage);
customElements.define("registry-chooser", RegistryChooser);
customElements.define("error-view", ErrorView);
customElements.define("identity-page", IdentityPage);
customElements.define("main-page", MainPage);
customElements.define("petition-card", Petition);
customElements.define("period-widget", PeriodWidget);
customElements.define("idp-widget", IDPWidget);
customElements.define("overlay-element", OverlayElement);
customElements.define("loading-spinner", LoadingSpinner);
customElements.define("create-petition", CreatePage);
customElements.define("measure-perf", PerfMeasure);
